### ISSUE TITLE
Missing return value

### ISSUE THREAD

**Issue by ickby** [WandererFan/freecad-dev#5]
Hello,

out of curiosity I compiled your drawing branch and played a bit with it. Nice work already!

It initially crashed for me on inserting views, the reason is a missing return value in FeatureViewPart::mustExecute() in case it must not recompute. Simply adding a return 0; line at the end  works. I use gcc under kubuntu 14.04.

Regards,
Stefan

**Comment by WandererFan** [comment]
fixed.  returns true/false as short.
